apiVersion: apps/v1 
kind: Deployment
metadata:
  name: PWC_SpamClassifier
spec:
  replicas: 1 
  template:
    spec:
      containers:
      - name: app
        image: tensorflow/tensorflow:latest-devel-py3
        command: ["/bin/sh", "-c"]
        args:
         - cd PWC_keras;
           pip install -r requirements.txt;
           python server.py;
        ports:
        - containerPort: 8080